### ISSUE TITLE
Constants decryption emulation does not support strings in params

### ISSUE THREAD

**Issue by BedTheGod** [cawk/ConfuserEx-Unpacker-2#11]
![9c8447b50be617d142661f83fe07c99b](https://user-images.githubusercontent.com/47125802/51872078-3bc4e680-2326-11e9-9eef-69a4e955b9bd.png)
so im trying to use this to emulate constants for a custom mod that has a string param in the constant decryption method, i have the params set correctly in the remover and have tested it with 3 uints, but with a string in the mix it does not work at least with 3 params anyways.
edit: so it is catching my string as case Code.Ldarga_S: and throwing the error.

**Comment by cawk** [comment]
Okay yes i need to add support for the Ldarda/S instructions, i am away from pc for around 7 days 
you can use this to add support for yourself 
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.ldarga?view=netframework-4.7.2

or i can look at it whenever i am back on my computer

**Comment by cawk** [comment]
okay it must mean that the ldarga instruction is not actually used after item is pushed on stack or you just got extremely lucky, if you need to add it properly i suppose look at ldloca that may give you an idea on how to implement, ill try get around to this soon
