### ISSUE TITLE
Unhandled exception: System.OverflowException: Overflow of an arithmetic operation.

### ISSUE THREAD

**Issue by Deltafox79** [cawk/ConfuserEx-Unpacker-2#12]
Hi mr cawk

I have this exception on this target : [vc.zip](https://github.com/cawk/ConfuserEx-Unpacker-2/files/2831973/vc.zip)

> using System;
> using System.Runtime.CompilerServices;
> using System.Security;
> 
> [module: SuppressIldasm]
> [module: ConfusedBy("ConfuserEx v0.6.0")]
> [module: UnverifiableCode]

**This is the exception :** 

> '.\ConfuserEx Unpacker.exe' .\vc.exe
> [!] Anti Tamper Detected
> [!] Anti Tamper Removed Successfully
> [!] Anti Tamper Detected
> [!] Anti Tamper Removed Successfully
> 
> Unhandled exception: System.OverflowException: Overflow of an arithmetic operation.
> in ConfuserEx_Unpacker.Protections.Lzma.Decompress(Byte[] data)
> in ConfuserEx_Unpacker.Protections.Utils.LzmaDecompress(Byte[] bytes)
> in System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
> in ConfuserEx_Unpacker.Protections.Utils.HandleCall(CallEventArgs args, Emulation emulation)
> in ConfuserEx_Unpacker.Protections.Constants.Remover.<>c.<InitaliseBytes>b__5_0(Emulation emulation, CallEventArgs args)
> in System.Action`2.Invoke(T1 arg1, T2 arg2)
> in CawkEmulatorV4.Emulation.<SetUp>b__8_1(Object sender, CallEventArgs e)
> in CawkEmulatorV4.Emulation.Emulate()
> in ConfuserEx_Unpacker.Protections.Constants.Remover.InitaliseBytes(MethodDef methods)
> in ConfuserEx_Unpacker.Protections.Constants.Remover.Deobfuscate()
> in ConfuserEx_Unpacker.Program.Main(String[] args)

Best Regards

**Comment by cawk** [comment]
Try run it again can take 2-3 times to run worked fine for me 
so will close this as this bug is to do with cawkemulator which i will look at one day if i have time
